version: '3'
services:
  yolo:
    image: "europe-docker.pkg.dev/isae-sdd-481407/isae-sdd-de-2526-docker/yolo-v11-backend:1.0"
    ports:
      - "8000:8000"
    hostname: yolo
  streamlit:
    image: "europe-docker.pkg.dev/isae-sdd-481407/isae-sdd-de-2526-docker/yolo-v11-frontend:1.0"
    ports:
      - "8501:8501"
    hostname: streamlit
